# Docker-compose.yml to run the NGINX webserver, MySQL Server, and librespeed servers.     - /isocmb_webserver/site.conf:/etc/nginx/conf.d/site.conf

version: '3'
services:
  web:
    image: nginx:latest
    container_name: webserver
    ports:
    - "80:80"
    volumes:
    - /home/isocmb/www/prod:/usr/share/nginx/html
    restart: unless-stopped
    links:
    - php
  php:
    image: php:7-fpm
    container_name: php
    volumes:
    - /home/isocmb/www/prod:/usr/share/nginx/html
  db:
    image: mysql
    container_name: mysql
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    - MYSQL_DATABASE=demodb
    restart: unless-stopped
  librespeed:
    image: ghcr.io/linuxserver/librespeed
    container_name: librespeed
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Winnipeg
      - PASSWORD=PASSWORD
      - CUSTOM_RESULTS=true #optional
      - DB_TYPE=sqlite #optional
      - DB_NAME=DB_NAME #optional
      - DB_HOSTNAME=DB_HOSTNAME #optional
      - DB_USERNAME=DB_USERNAME #optional
      - DB_PASSWORD=DB_PASSWORD #optional
    volumes:
      - /path/to/appdata/config:/config
    ports:
      - 8081:8081
    restart: unless-stopped
